language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - npm install -g now@canary
deploy:
  - provider: script
    script: now -t $NOW_TOKEN -T ngvenezuela -A now-staging.json && now alias -t $NOW_TOKEN -T ngvenezuela -A now-staging.json -y && now rm wengy-ven -t $NOW_TOKEN -T ngvenezuela --safe -y
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: now -t $NOW_TOKEN -T ngvenezuela && now alias -t $NOW_TOKEN -T ngvenezuela -y && now rm wengy-ven -t $NOW_TOKEN -T ngvenezuela --safe -y
    skip_cleanup: true
    on:
      branch: master
